require('../../../../common/vendor.js');(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["packageDecoration/components/uv-link/components/uv-link/uv-link"],{"01cb":function(t,n,e){"use strict";e.r(n);var i=e("4d5e"),a=e("74aa");for(var u in a)["default"].indexOf(u)<0&&function(t){e.d(n,t,(function(){return a[t]}))}(u);e("2156");var o=e("f0c5"),c=Object(o["a"])(a["default"],i["b"],i["c"],!1,null,"2863469a",null,!1,i["a"],void 0);n["default"]=c.exports},"206b":function(t,n,e){},2156:function(t,n,e){"use strict";var i=e("206b"),a=e.n(i);a.a},"4d5e":function(t,n,e){"use strict";e.d(n,"b",(function(){return i})),e.d(n,"c",(function(){return a})),e.d(n,"a",(function(){}));var i=function(){var t=this.$createElement,n=(this._self._c,this.__get_style([this.linkStyle,this.$uv.addStyle(this.customStyle)]));this.$mp.data=Object.assign({},{$root:{s0:n}})},a=[]},"74aa":function(t,n,e){"use strict";e.r(n);var i=e("b408"),a=e.n(i);for(var u in i)["default"].indexOf(u)<0&&function(t){e.d(n,t,(function(){return i[t]}))}(u);n["default"]=a.a},b408:function(t,n,e){"use strict";(function(t){var i=e("4ea4");Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var a=i(e("44ce")),u=i(e("b3ce")),o=i(e("202d")),c={name:"uv-link",emits:["click"],mixins:[a.default,u.default,o.default],computed:{linkStyle:function(){var t={color:this.color,fontSize:this.$uv.addUnit(this.fontSize),lineHeight:this.$uv.addUnit(this.$uv.getPx(this.fontSize)+2),textDecoration:this.underLine?"underline":"none"};return t}},methods:{openLink:function(){var n=this;t.setClipboardData({data:this.href,success:function(){t.hideToast(),n.$nextTick((function(){toast(n.mpTips)}))}}),this.$emit("click")}}};n.default=c}).call(this,e("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'packageDecoration/components/uv-link/components/uv-link/uv-link-create-component',
    {
        'packageDecoration/components/uv-link/components/uv-link/uv-link-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("01cb"))
        })
    },
    [['packageDecoration/components/uv-link/components/uv-link/uv-link-create-component']]
]);
