(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["packageVote/components/activity-card"],{"22eb":function(t,i,e){"use strict";e.r(i);var n=e("5339"),a=e("bed6");for(var r in a)["default"].indexOf(r)<0&&function(t){e.d(i,t,(function(){return a[t]}))}(r);e("8f8d");var u=e("f0c5"),c=Object(u["a"])(a["default"],n["b"],n["c"],!1,null,null,null,!1,n["a"],void 0);i["default"]=c.exports},5339:function(t,i,e){"use strict";e.d(i,"b",(function(){return n})),e.d(i,"c",(function(){return a})),e.d(i,"a",(function(){}));var n=function(){var t=this.$createElement;this._self._c},a=[]},"8f8d":function(t,i,e){"use strict";var n=e("e19e"),a=e.n(n);a.a},bed6:function(t,i,e){"use strict";e.r(i);var n=e("e8aa"),a=e.n(n);for(var r in n)["default"].indexOf(r)<0&&function(t){e.d(i,t,(function(){return n[t]}))}(r);i["default"]=a.a},e19e:function(t,i,e){},e8aa:function(t,i,e){"use strict";Object.defineProperty(i,"__esModule",{value:!0}),i.default=void 0;var n={name:"activityCard",props:{activity:{type:Object,default:{}},mode:{type:String,default:"simple"}},computed:{coverImage:function(){return this.activity&&this.activity.fileUrl?this.getImageHttpUrl(this.activity.fileUrl):""},displayendDate:function(){if(this.activity.endDate){var t=this.$tool.date.parse(this.activity.endDate);return this.$tool.date.format(t,"yyyy/MM/dd hh:mm")}return""},displayButtonText:function(){if(this.activity){if(1==this.activity.status)return"未开始";if(2==this.activity.status)return"进行中";if(3==this.activity.status)return"已结束";if(-1==this.activity.status)return"已下线";if(0==this.activity.status)return"未发布"}return""}},methods:{getImageHttpUrl:function(t){return t?this.$tool.image.getHttpUrl(t):""},onClick:function(){this.$emit("click")}}};i.default=n}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'packageVote/components/activity-card-create-component',
    {
        'packageVote/components/activity-card-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("22eb"))
        })
    },
    [['packageVote/components/activity-card-create-component']]
]);
