require('../../../../common/vendor.js');(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["packageDecoration/components/uv-text/components/uv-text/uv-text"],{"2ffc":function(e,t,n){"use strict";n.r(t);var o=n("668c"),i=n.n(o);for(var c in o)["default"].indexOf(c)<0&&function(e){n.d(t,e,(function(){return o[e]}))}(c);t["default"]=i.a},"668c":function(e,t,n){"use strict";(function(e){var o=n("4ea4");Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var i=o(n("8fad")),c=o(n("44ce")),u=o(n("b3ce")),l=o(n("f5c0")),a=o(n("f329")),s=o(n("42c8")),r={name:"uv-text",emits:["click"],mixins:[c.default,u.default,i.default,l.default,a.default,s.default],components:{uvLink:function(){Promise.all([n.e("packageDecoration/common/vendor"),n.e("packageDecoration/components/uv-link/components/uv-link/uv-link")]).then(function(){return resolve(n("01cb"))}.bind(null,n)).catch(n.oe)},uvIcon:function(){Promise.all([n.e("packageDecoration/common/vendor"),n.e("packageDecoration/components/uv-icon/components/uv-icon/uv-icon")]).then(function(){return resolve(n("19e8"))}.bind(null,n)).catch(n.oe)}},computed:{valueStyle:function(){var e={textDecoration:this.decoration,fontWeight:this.bold?"bold":"normal",wordWrap:this.wordWrap,fontSize:this.$uv.addUnit(this.size)};return!this.type&&(e.color=this.color),this.isNvue&&this.lines&&(e.lines=this.lines),this.lineHeight&&(e.lineHeight=this.$uv.addUnit(this.lineHeight)),!this.isNvue&&this.block&&(e.display="block"),this.$uv.deepMerge(e,this.$uv.addStyle(this.customStyle))},isNvue:function(){return!1},isMp:function(){return!0,!0}},data:function(){return{}},methods:{clickHandler:function(){this.call&&"phone"===this.mode&&e.makePhoneCall({phoneNumber:this.text}),this.$emit("click")}}};t.default=r}).call(this,n("543d")["default"])},"98e1":function(e,t,n){"use strict";n.r(t);var o=n("f71e"),i=n("2ffc");for(var c in i)["default"].indexOf(c)<0&&function(e){n.d(t,e,(function(){return i[e]}))}(c);n("fca2");var u=n("f0c5"),l=Object(u["a"])(i["default"],o["b"],o["c"],!1,null,"7c73c878",null,!1,o["a"],void 0);t["default"]=l.exports},f5b5:function(e,t,n){},f71e:function(e,t,n){"use strict";n.d(t,"b",(function(){return o})),n.d(t,"c",(function(){return i})),n.d(t,"a",(function(){}));var o=function(){var e=this,t=e.$createElement,n=(e._self._c,e.show&&"price"===e.mode?e.__get_style([e.valueStyle]):null),o=e.show&&e.prefixIcon?e.$uv.addStyle(e.iconStyle):null,i=e.show&&"link"!==e.mode&&e.openType&&e.isMp?e.__get_style([e.valueStyle]):null,c=!e.show||"link"===e.mode||e.openType&&e.isMp?null:e.__get_style([e.valueStyle]),u=e.show&&e.suffixIcon?e.$uv.addStyle(e.iconStyle):null;e.$mp.data=Object.assign({},{$root:{s0:n,g0:o,s1:i,s2:c,g1:u}})},i=[]},fca2:function(e,t,n){"use strict";var o=n("f5b5"),i=n.n(o);i.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'packageDecoration/components/uv-text/components/uv-text/uv-text-create-component',
    {
        'packageDecoration/components/uv-text/components/uv-text/uv-text-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("98e1"))
        })
    },
    [['packageDecoration/components/uv-text/components/uv-text/uv-text-create-component']]
]);
