(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["packageZS/components/position-select"],{"32c8":function(i,e,n){"use strict";var t=n("4ea4");Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var d=t(n("448a")),u=(t(n("7504")),{props:{regionList:{type:Array,default:[]}},data:function(){return{selectedRegion:{id:-1,text:"不限"},selectedBuilding:[{id:-1,name:"不限"}],buildingList:[]}},computed:{getNewList:function(){return[{id:-1,text:"不限"}].concat((0,d.default)(this.regionList))}},created:function(){console.log(this.selectedBuilding)},methods:{reset:function(){this.selectedRegion={id:-1,text:"不限"},this.selectedBuilding=[{id:-1,name:"不限"}],this.buildingList=[]},handleClickRegion:function(i){this.selectedRegion.id!=i.id&&(this.selectedBuilding=[],this.selectedRegion=i,-1==i.id&&this.reset(),this.getBuilding(i.id))},getBuilding:function(i){var e=this;this.$http.request("/api/v1.0/CommonDataApi/BuildingsSelector?regionId=".concat(i)).then((function(i){i&&(e.buildingList=[{id:-1,name:"不限"}].concat((0,d.default)(i)))}))},handleClickBuilding:function(i){-1==i.id&&(this.selectedBuilding=[{id:-1,name:"不限"}]);var e=[];e=this.selectedBuilding.filter((function(i){return-1!=i.id}));var n=e.findIndex((function(e){return e.id==i.id}));n>=0?(e.splice(n,1),this.selectedBuilding=e):(e.push(i),this.selectedBuilding=e)},submit:function(){this.$emit("handleOk",{regionId:-1==this.selectedRegion.id?void 0:this.selectedRegion.id,buildingIds:this.selectedBuilding.filter((function(i){return-1!=i.id})).map((function(i){return i.id}))})}}});e.default=u},bbaf:function(i,e,n){"use strict";var t=n("eb34"),d=n.n(t);d.a},c6b9:function(i,e,n){"use strict";n.d(e,"b",(function(){return d})),n.d(e,"c",(function(){return u})),n.d(e,"a",(function(){return t}));var t={uniIcons:function(){return Promise.all([n.e("common/vendor"),n.e("uni_modules/uni-icons/components/uni-icons/uni-icons")]).then(n.bind(null,"cff5"))}},d=function(){var i=this,e=i.$createElement,n=(i._self._c,i.__map(i.buildingList,(function(e,n){var t=i.__get_orig(e),d=i.selectedBuilding.find((function(i){return i.id==e.id})),u=-1!=e.id&&i.selectedBuilding.find((function(i){return i.id==e.id})),c=-1!=e.id&&!i.selectedBuilding.find((function(i){return i.id==e.id}));return{$orig:t,g0:d,g1:u,g2:c}})));i.$mp.data=Object.assign({},{$root:{l0:n}})},u=[]},d874:function(i,e,n){"use strict";n.r(e);var t=n("c6b9"),d=n("e0c5");for(var u in d)["default"].indexOf(u)<0&&function(i){n.d(e,i,(function(){return d[i]}))}(u);n("bbaf");var c=n("f0c5"),o=Object(c["a"])(d["default"],t["b"],t["c"],!1,null,"66f52f60",null,!1,t["a"],void 0);e["default"]=o.exports},e0c5:function(i,e,n){"use strict";n.r(e);var t=n("32c8"),d=n.n(t);for(var u in t)["default"].indexOf(u)<0&&function(i){n.d(e,i,(function(){return t[i]}))}(u);e["default"]=d.a},eb34:function(i,e,n){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'packageZS/components/position-select-create-component',
    {
        'packageZS/components/position-select-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("d874"))
        })
    },
    [['packageZS/components/position-select-create-component']]
]);
