(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["packageZS/components/resource-list"],{"4d51":function(e,t,n){"use strict";n.r(t);var o=n("fd29"),r=n.n(o);for(var u in o)["default"].indexOf(u)<0&&function(e){n.d(t,e,(function(){return o[e]}))}(u);t["default"]=r.a},acef:function(e,t,n){"use strict";n.d(t,"b",(function(){return o})),n.d(t,"c",(function(){return r})),n.d(t,"a",(function(){}));var o=function(){var e=this,t=e.$createElement,n=(e._self._c,e.__map(e.list,(function(t,n){var o=e.__get_orig(t),r=e.itemTitle(t),u=t.tagList&&t.tagList.length>0;return{$orig:o,m0:r,g0:u}})));e.$mp.data=Object.assign({},{$root:{l0:n}})},r=[]},b00c:function(e,t,n){"use strict";n.r(t);var o=n("acef"),r=n("4d51");for(var u in r)["default"].indexOf(u)<0&&function(e){n.d(t,e,(function(){return r[e]}))}(u);n("cfe6");var c=n("f0c5"),i=Object(c["a"])(r["default"],o["b"],o["c"],!1,null,"7eb62e38",null,!1,o["a"],void 0);t["default"]=i.exports},c5b9:function(e,t,n){},cfe6:function(e,t,n){"use strict";var o=n("c5b9"),r=n.n(o);r.a},fd29:function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var o={components:{NoImgDefault:function(){n.e("components/no-img-default/no-img-default").then(function(){return resolve(n("5a1b"))}.bind(null,n)).catch(n.oe)}},props:{list:{type:Array,default:[]}},data:function(){return{}},methods:{gotoDetail:function(t){e.navigateTo({url:"/packageZS/house-resource-detail?id=".concat(t)})},itemTitle:function(e){var t=(e.resourceDistrict||"")+" "+(e.resourceBuildingNo||"")+" "+(e.resourceUnit||"")+" "+(e.resourceFloor||"")+" "+(e.resourceCode||"");return t.length>26?(e.resourceBuildingNo||"")+" "+(e.resourceUnit||"")+" "+(e.resourceFloor||"")+" "+(e.resourceCode||""):t}}};t.default=o}).call(this,n("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'packageZS/components/resource-list-create-component',
    {
        'packageZS/components/resource-list-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("b00c"))
        })
    },
    [['packageZS/components/resource-list-create-component']]
]);
